language:php

php:
  - 5.6
  - 7.0

script: find {src,tests} -name "*.php" ! -path '*/NonPHP7.php' -print0 | xargs -0 -n1 -P8 php -l

after script:
notification:
  recipients:
  - augusto.berwaldt@gmail.com
